### ISSUE TITLE
Not able to load in Flow data on Lumen 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-api#114]
# Context 
When loading data from akvoflow-67 into Lumen directly for one particular survey form the loading fails and shows a Failed to load with either a 502 or a 500 error. If the user imports the data via csv there are no issues. The loading error does not happen with other forms from this instance. 

The survey form in mind is: Myanmar > Micro finance study > CLCMGOMP Project > form ID: 131061967. The form has 929 questions where many of them are option questions with codes. 175 submissions are made to it, with no repeated question groups and some non latin characters are used. 

The error can be found on: https://lumen.akvotest.org/library

<img width="417" alt="screen shot 2018-01-25 at 15 08 45" src="https://user-images.githubusercontent.com/12456965/35392271-a9761c60-01e1-11e8-9977-5d4954b7c04f.png">

There is no other error on console. 

@kardan (through @nadiagorchakova) shared that the issue is most likely on Flow API's side and the error shown in Lumen's web interface is what they receive from Flow's API.  

@muloem could you take a look at the issue? Thanks

**Comment by muloem** [comment]
From what I can find currently the issue is related to the querying of GAE via the RemoteApi.  The call to return the results through an Iterator is hanging and never returns.  So when there is a timeout, nginx returns 499 error status
