### ISSUE TITLE
Update documentation with variableName

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-api#117]
Make sure the Wiki holds details on and properly explains variableName

https://github.com/akvo/akvo-flow-api/issues/89

**Comment by janagombitova** [comment]
@muloem and @kymni with the changes released yesterday, who from the two of you will make sure the variable names are documented in the Wiki?

**Comment by kymni** [comment]
We could update the [question elements table](https://github.com/akvo/akvo-flow-api/wiki/Akvo-Flow-REST-API#question-elements) with the full list of properties complete with a description for each
