### ISSUE TITLE
When reading variableName, need to check renamed field before legacy field

### ISSUE THREAD

**Issue by stellanl** [akvo/akvo-flow-api#118]
When fetching variableName the code should only read from the legacy field if the new one is null/nil.
https://github.com/akvo/akvo-flow-api/blob/1835c9c4537134fa8cfe8a6a967a0056aff09dc8/api/src/clojure/org/akvo/flow_api/datastore/survey.clj#L29
 See #89.

**Comment by janagombitova** [comment]
@muloem Can this issue be closed now?
