### ISSUE TITLE
Use camel case for request parameters

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-api#132]
We currently use underscore case for parameters in the API urls.  However, we have had lots of support requests and confusion regarding this that we decided to support camelCase, while keeping the current implementation in place till further notice.

```
https://api.akvo.org/flow/orgs/<org>/folders?parent_id=<parent_id>
https://api.akvo.org/flow/orgs/<org>/surveys?folder_id=<folder_id>
https://api.akvo.org/flow/orgs/<org>/surveys/<survey_id>
https://api.akvo.org/flow/orgs/<org>/data_points?survey_id=<survey-id>
https://api.akvo.org/flow/orgs/<org>/form_instances?survey_id=<survey_id>&form_id=<form_id>
```

**Comment by dlebrero** [comment]
What about https://api.akvo.org/flow/orgs/<org>/form_instances <-- form_instances? Do we want that to be camelCase also?

**Comment by muloem** [comment]
I think for now we'll keep it to the parameters but we can have a chat together with @iperdomo who was there when we discussed this originally to figure out whether to convert that as well.
