### ISSUE TITLE
Flumenfly permissions API

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow-api#146]
Add endpoint for Lumen to be able to honour Flow permissions for surveys.

Two options:

1. Input: list of Flow instances
   Output: list of surveys per Flow instance

2. Input: list of surveys (== survey-id + flow instance)
   Ouput: subset of input surveys that the user can see.

**Comment by dlebrero** [comment]
@muloem @kardan I do not have a strong opinion on which option is better. 

The first option is more generally reusable, the second option is more narrow (which gives flow-api more freedom to change implementation).

The first one has small input, potentially big output.
The second, given the current Lumen usage, would have small input/output.

Given that this API is just a stepping stone towards the final solution, I think I prefer option 2.

**Comment by dlebrero** [comment]
Opted for the second option, as it is going to be more similar to the API that we will have to implement in the "grouping things app".

See https://github.com/akvo/akvo-flow-api/commit/d048daa28442895461333444256028f591140362#diff-ce2918b091fb17074c7e4772fbc54a6cR41 for an example of how the api looks like.

The result will be just the same list sent by Lumen, but with anything not allowed filtered out.  

I will change the  "/flumenfly" path if we all are happy with the approach

**Comment by kardan** [comment]
I had the second option in mind so I'm happy with were you landed.

**Comment by muloem** [comment]
I was only wondering whether the Lumen backend will already have the list of survey ids in order to make that query to the API.  Otherwise I would also vote for option 2.
