### ISSUE TITLE
Cache unknown users

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow-api#154]
Users that do not have access to an instance are not being cached, which means that we end up hitting the Datastore for any request made by that user. 

This is specially noticeable in the new Flumenfly check_permissions endpoint, as it is quite possible that this situation happens.

**Comment by stellanl** [comment]
How long is the cache timeout? We also don't want people to have to wait too long after they get access until they can use it.

**Comment by dlebrero** [comment]
10 mins.
