### ISSUE TITLE
Flow-api internal service call not working from lumen service, 404 status

### ISSUE THREAD

**Issue by tangrammer** [akvo/akvo-flow-api#178]
Relates #166 
Trying from lumen-backend this url http://flow-api-internal/flow/orgs/uat1/surveys/4220455 with :opts `{:connection-timeout 2000, :connection-request-timeout 50, :socket-timeout 5000, :headers {User-Agent lumen, Accept application/vnd.akvo.flow.v2+json, X-Akvo-Email juan@akvo.org}, :as :json}` returns `404`

**Comment by dlebrero** [comment]
Remove the /flow/ (see the nginx proxies about why)
