### ISSUE TITLE
Create migration guide from Keycloak to Auth0

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow-api#188]
We still support both Keycloak and Auth0, but we will want all partners that use the Flow API to move to Auth0 so that we can decommission Keycloak.

Given that we have to give partners enough time to do the work (~6 months), it will be nice to start roll the ball asap. 

Before we are able to tell partners about the required work, we need to provide some "Migration guide" with the steps required and update any documentation related to authentication.

**Comment by tangrammer** [comment]
Relates to https://github.com/akvo/akvo-lumen/issues/2419

**Comment by tangrammer** [comment]
here first doc version
https://github.com/akvo/akvo-flow-api/wiki/Akvo-SSO-login

one thing that i realised now is the big `expire_time` of the `access_token` ... current production value is 86400 secs => 24 hours ... being the `expire_time` of jwt_token to `36000` => 10 hours

@iperdomo what do you think will be a good time frame for that `access_token`?

**Comment by tangrammer** [comment]
Once all details were verified/reviewed align changes with  https://github.com/akvo/akvo-lumen/issues/2419

**Comment by dlebrero** [comment]
Can we close this?
