### ISSUE TITLE
Support for filtering data on Form instances

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow-api#192]
Support for filtering data based on `collectionDate`
The user should be able to use inequality operators:
* `>=` - Greater or equal than
* `>`   - Greater than
* `<=` - Less or equal than
* `<`   - Less than

The value passed as parameter must be a timestamp. The supported formats:
* [Epoch](https://en.wikipedia.org/wiki/Unix_time)
* [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601)

Example (represent the same timestamp)

* `submission_date>=1573480968`
* `submission_date>=2019-11-11T14:02:48Z`

### Technical details
* We don't need to create an extra index on Flow datastore as we already have composite index `SurveyId` `collectionDate`
* The sorting of `collectionDate` is descending, so the user will get the most recent dates first, and then go backwards (if she/he keeps reading using a cursor)

**Comment by iperdomo** [comment]
The actual call needs to [URLEncode](https://en.wikipedia.org/wiki/Query_string#URL_encoding) the expression to be used as filter, e.g. 

    https://api.akvo.org/flow/orgs/<organization-subdomain>/form_instances?survey_id=<survey-id>&form_id=<form_id>&submission_date=%3E%3D1573480968

In this example `submission_date=%3E%3D1573480968` means `submission_date` filtered by `>=1573480968`

* `>=` -> `%3E%3D`
* `>` -> `%3E`
* `<=` -> `%3C%3D`
* `<` -> `%3C`

https://github.com/akvo/akvo-flow-api/wiki/Akvo-Flow-REST-API#retrieving-collected-data

**Comment by muloem** [comment]
@iperdomo One question here. Is it possible to include multiple `submission_date` filters in the URL? i.e if one decided to only download data with a specific period like `submission_date=>=1Nov&submission_date=<30Nov`  What happens if a user enters that?

**Comment by iperdomo** [comment]
@muloem nope there is no support for multiple inequality expressions. Also the supported Date/time value must be a number representing a date/time in "Unix time", or a full ISO-8601 string.

**Comment by muloem** [comment]
So the API will behave as expected if multiple expressions are entered or will it go belly up?

**Comment by iperdomo** [comment]
See the current state...
The test

```sh

# $token is a Bearer token obtained from the Identity Provider

echo 'All instances'

curl --silent \
     --header "Content-Type: application/json" \
     --header "Accept: application/vnd.akvo.flow.v2+json" \
     --header "Authorization: Bearer $token" \
     --url "https://api-auth0.akvo.org/flow/orgs/uat1/form_instances?survey_id=557939116&form_id=577429120" | jq -M '.formInstances[] | {id, submissionDate}'

echo 'filter by <=2019-12-18T11:27:27Z'

curl --silent \
     --header "Content-Type: application/json" \
     --header "Accept: application/vnd.akvo.flow.v2+json" \
     --header "Authorization: Bearer $token" \
     --url "https://api-auth0.akvo.org/flow/orgs/uat1/form_instances?survey_id=557939116&form_id=577429120&submission_date=%3C%3D2019-12-18T11:27:27Z" | jq -M '.formInstances[] | {id, submissionDate}'

echo 'Multiple filter expression - Only applies the first inequality'

curl --silent \
     --header "Content-Type: application/json" \
     --header "Accept: application/vnd.akvo.flow.v2+json" \
     --header "Authorization: Bearer $token" \
     --url "https://api-auth0.akvo.org/flow/orgs/uat1/form_instances?survey_id=557939116&form_id=577429120&submission_date=%3C%3D2019-12-18T11:27:27Z&submission_date%3E%3D2019-12-18T11:27:27Z" | jq -M '.formInstances[] | {id, submissionDate}'

```

Result
```
All instances
{
  "id": "561949131",
  "submissionDate": "2019-12-18T11:26:54Z"
}
{
  "id": "561949134",
  "submissionDate": "2019-12-18T11:29:17Z"
}
{
  "id": "564029131",
  "submissionDate": "2019-12-18T11:27:00Z"
}
{
  "id": "568069142",
  "submissionDate": "2019-12-18T11:27:27Z"
}
filter by <=2019-12-18T11:27:27Z
{
  "id": "564029131",
  "submissionDate": "2019-12-18T11:27:00Z"
}
{
  "id": "561949131",
  "submissionDate": "2019-12-18T11:26:54Z"
}
Multiple filter expression - Only applies the first inequality
{
  "id": "564029131",
  "submissionDate": "2019-12-18T11:27:00Z"
}
{
  "id": "561949131",
  "submissionDate": "2019-12-18T11:26:54Z"
}
```
