### ISSUE TITLE
Support for machine-to-machine JWT tokens

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow-api#195]
In the transition to Auth0 we have now the need of supporting tokens where the `email` claim is not part of the JWT. For this we need to use the `/userinfo` endpoint and extract the `email` if present and valid.
The Initial request **must** contain the scopes `openid` and `email`, e.g.
````
curl --silent \
     --request POST \
     --url "https://<tenant>.eu.auth0.com/oauth/token" \
     --header "content-type: application/x-www-form-urlencoded" \
     --data "grant_type=password" \
     --data "username=${EMAIL}" \
     --data "password=${PASSWORD}" \
     --data "audience=http://akvo.org" \
     --data "scope=openid email" \                ## <-- important
     --data "client_id=${CLIENT_ID}"
````

The proxy will check if the `email` claim is part of the JWT or call the `/userinfo` endpoint before returning HTTP 403 to the user.

Related to issue #192

**Comment by dlebrero** [comment]
Can we close?
