### ISSUE TITLE
Evaluate caching responses other than HTTP 204

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow-api#204]
We could benefit from serving cached results via nginx instead of reading unchanged data via Remote API.
Some questions:
* For how long do we want to cache responses, few mins? hours?
* Is the user requesting a particular resource part of the `proxy_cache_key` variable ?

**Comment by dlebrero** [comment]
> Is the user requesting a particular resource part of the proxy_cache_key variable ?

Yes, due to permissions
