### ISSUE TITLE
Gracefully handle HTTP 503 when daily quota is reached

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow-api#210]
When reading data via GAE Remote API, if the instance has reached its daily quota, GAE returns HTTP 503, and we log the event as a crash in sentry.

- [ ] Log the exception as _info_ (to not miss the problem)
- [ ] Return appropriate HTTP code to the client, e.g. HTTP 429 (Too many requests)

**Comment by iperdomo** [comment]
HTTP 503 could be the right status code

**Comment by dlebrero** [comment]
Doesn't a 5xx mean that the issue is in the server side? I think this case the issue is in the client calling too many teams, so it should be a 4xx code

**Comment by iperdomo** [comment]
After rev 8472801 
````
< HTTP/2 429 
< server: openresty
< date: Mon, 02 Mar 2020 06:11:40 GMT
< content-type: application/json; charset=utf-8
< content-length: 69
< access-control-allow-origin: *
< access-control-allow-credentials: true
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: Accept,Accept-Encoding,Accept-Language,Authorization,Connection,DNT,Host,Origin,Referer,User-Agent
< via: 1.1 google
< alt-svc: clear
< 
* Connection #0 to host api-auth0.akvotest.org left intact
{"message":"This application is temporarily over its serving quota."}
````
