### ISSUE TITLE
Question on CORS headers

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow-api#70]
@iperdomo Could we add `Content-Type` to the list of allowed methods here https://github.com/akvo/akvo-flow-api/blob/develop/nginx/nginx.conf#L36?

**Comment by iperdomo** [comment]
@jonase sure we can, what's the current use case? We don't support PUT nor POST requests

> Content-Type | The MIME type of the body of the request (used with POST and PUT requests) | 
Content-Type: application/x-www-form-urlencoded | Permanent

https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
