### ISSUE TITLE
Restructure responses layout

### ISSUE THREAD

**Issue by iperdomo** [akvo/akvo-flow-api#76]
In the presentation of the preview version of the API @muloem raised the issue that the layout of the responses feels _strange_.

Right now, the data looks like this:
````
    formInstances: [
    {
       deviceIdentifier:
       dataPointId:
       submissionDate:
       modifiedAt:
       createdAt:
       responses: {
         questionId1: { 
           iteration0: <value>
         },
         questionId2: {
           iteration0: <value>
         }
       }
       // [...]
    },
    // [...]
   ]
````
As example:
````
{
  "formInstances": [
    {
      "deviceIdentifier": "<IDENT>",
      "dataPointId": "7293384",
      "submissionDate": "2017-02-16T15:18:41Z",
      "modifiedAt": "2017-02-16T15:26:12.384Z",
      "id": "1293492",
      "responses": {
        "3290007": {
          "0": {
            "lat": 15.031715060644512,
            "long": -91.14701983321523,
            "elev": 2001.5,
            "code": "j6jpqtym"
          }
        },
        "6250004": {
          "0": {
            "filename": "https://path/to/file.jpg",
            "location": {
              "longitude": -91.14701441467996,
              "altitude": 2007.284820787274,
              "latitude": 15.031726374129304,
              "accuracy": 1.5
            }
          }
        },
        "7280006": {
          "0": "2017-02-12T00:00:00Z"
        },
[...]
````

Having the iteration as a string and question level feels _wrong_. 

Since the _repeatable_ parts are _Question Groups_, we could include the questionGroupId as part of the response, and have an array that implicitly defines the iterations.

cc/ @muloem @jonase

**Comment by iperdomo** [comment]
I guess the idea is to have the questionGroup as part of the response:
````
    formInstances: [
    {
       deviceIdentifier:
       dataPointId:
       submissionDate:
       modifiedAt:
       createdAt:
       responses: {
         questionGroupId1: [    // repeatable
           {questionId1: <value>, questionId2: <value>, quesitonId3: <value>}, // iter0 
           {questionId1: <value>, questionId2: <value>, quesitonId3: <value>}, // iter1
         ],
         questionGroupId2: [    // non-repeatable
           {questionIdX: <value>, questionIdZ: <value>} // just one iteration
         ] 
       }
       // [...]
    },
    // [...]
   ]
````

**Comment by jonase** [comment]
@iperdomo yes, I think this is more "correct" since it's question groups that are iterated on.

**Comment by muloem** [comment]
Agree with @jonase. it feels more right to have it setup this way. One question though, in the survey definition, we have the notion of order of questions and question groups through the lists that are returned right? i.e. we don't return an `order` element for any of these objects?  I ask because if each iteration is an object with the question ids as keys, users may want to have some kind of ordering and would perhaps need to refer to the survey definition.

**Comment by iperdomo** [comment]
@muloem yes, to know the order, you need the survey definition. In the same way we're not including the _Question text_ in the response, just the _Question Id_
