### ISSUE TITLE
Responses for non-existing questions

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow-api#82]
We rely on the form definition to parse responses. If we see a response for a question that does not exist (perhaps it has been deleted) we can not properly parse the response. 

We could potentially include the response as a raw string, but then the api consumer faces the exact same problem about what to do with it.

As long as we don't have proper form/response versioning in Flow I think the best approach is to drop the answer and not include it in the api response.

**Comment by iperdomo** [comment]
@muloem an answer (`QuestionAnswerStore`) without a definition (`Question`) is not _reachable_ by a Flow user. By reachable I mean that a user can't see that answer anywhere in the system: Data tab, Reports

I think discarding the answer is the best way to handle it, and is similar to what Flow is doing at the moment.

**Comment by muloem** [comment]
I agree. if the answer doesn't have a corresponding question then it should be dropped.  I already mentioned to @jonase that we infact had a check for whether there are any answers when deleting questions. and we prevent that from happening.

**Comment by jonase** [comment]
This one is merged and can be closed.
