### ISSUE TITLE
Should we support old option response format?

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow-api#86]
Currently option responses are encoded as something similar to `[{"text": "A", "code": "a"}]`.

I think there exists an older option response format that encoded responses as `A` (perhaps `A|B|C` in the case of multiple selections). Should the Flow api support these formats? How many instances are still in active use that uses this format?

**Comment by iperdomo** [comment]
I think is _required_ since there is a lot of _legacy data_ in some large instances

**Comment by jonase** [comment]
closing this one as done.
