### ISSUE TITLE
Add question ID 

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-api#89]
When a user defines a form and its questions, sometimes they define something we call in Flow: **question ID**.

The question ID can be understood as a variable name. The question ID then replaces the long question text in the column headers to ease up the analysis and understanding of data. Secondly, sometimes partners have their databases (governments) set up that they do not identify new data by the question text (as that can easily change) but by the question IDs. 

Users import Flow data into their databases or analytical tools currently using the exports, but ideally we want them to use the API, so providing the question ID they have created will be valuable. Secondly, for Lumen users, user will not have to recreate the column labels, if they have created them already in Flow. 

Please note that we are currently thinking of changing the name of **question ID** to something our users recognise and to something we do not internally confuse with the Flow given question IDs. For more info see this issue: https://github.com/akvo/akvo-flow/issues/2170

**Comment by jonase** [comment]
Here's the associated issue in the lumen repo: https://github.com/akvo/akvo-lumen/issues/964

I'm in favour of adding support for this. The implementation itself is easy once we find a good new name (instead of `question ID`). How about the longer name `identifier`?

**Comment by janagombitova** [comment]
@jonase We have been talking about the name here: https://github.com/akvo/akvo-flow/issues/2170#issuecomment-315983324 If you have any comments please do share

**Comment by janagombitova** [comment]
@muloem Can this issue be closed now?

**Comment by janagombitova** [comment]
@muloem We can close this one now, right?

**Comment by janagombitova** [comment]
@muloem Bump
