### ISSUE TITLE
Keycloak authentication needed

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow-api#90]
*Note: This issue is based on the feedback from the early adopter testing* 

To be able to use Flow's API currently, not only does the user need to have a Flow user account but also a Keycloak account. Keycloak is not being used in Flow at the moment for authentication what means that the user needs to set up this account before she can use the API. 

We either need to, in the Wiki, mention this requirement and give our users a way how to create a Keycloak account. Or we need to ensure all Flow users have a Keycloak account to skip this step on the user's side. Or we need to allow Flow users to use the API with their google account they logged into Flow with

**Comment by dlebrero** [comment]
Flow API is already integrated with Auth0
